"""users: the account root table

Creates ``users`` on top of the enabled-pgvector baseline: the server-minted
identity every other domain table references. ``id`` is a ``GENERATED BY DEFAULT
AS IDENTITY`` bigint so ids are server-minted; ``email`` is unique. Constraint
names follow the deterministic convention (``pk_users`` / ``uq_users_email``) so
downgrades are reversible. The accounts domain adds its ORM model and session
tables in a later slice.

Revision ID: 0002_users
Revises: 0001_baseline
Create Date: 2026-07-20

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0002_users"
down_revision: str | None = "0001_baseline"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )


def downgrade() -> None:
    op.drop_table("users")
